import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav style={{backgroundColor:"#133238",
         
          color : "white",
          padding: "1rem",
          display:"flex",
          justifyContent:"center",
          gap:"12rem",
          fontSize:"1.125rem",

        }}>
          {" "}
         <Link href="/"> Home </Link>
         <Link href="/about"> about </Link>
         <Link href="/contact"> contact </Link>
         <Link href="/users"> Users </Link>
       </nav>
        {children}
        
      </body>  
    </html>
  );
}
